# Generated by Django 4.0.1 on 2022-01-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blog_alter_doctor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='medicine',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
